INSERT INTO depo (code, name) VALUES ('0001','HCO');
INSERT INTO depo (code, name) VALUES ('0002','BANDUNG');
INSERT INTO depo (code, name) VALUES ('0003','KOPERASI');
INSERT INTO depo (code, name) VALUES ('0004','GEDEBAGE');
INSERT INTO depo (code, name) VALUES ('0005','SUKABUMI');
INSERT INTO depo (code, name) VALUES ('0006','CIMAREME');
INSERT INTO depo (code, name) VALUES ('0007','GARUT');
INSERT INTO depo (code, name) VALUES ('0008','CIREBON');
INSERT INTO depo (code, name) VALUES ('0009','MAJALAYA');
INSERT INTO depo (code, name) VALUES ('0010','BANJARAN');
INSERT INTO depo (code, name) VALUES ('0011','PDU - BANDUNG');
INSERT INTO depo (code, name) VALUES ('0012','SUMEDANG');
INSERT INTO depo (code, name) VALUES ('0013','CIANJUR');
INSERT INTO depo (code, name) VALUES ('0014','TASIKMALAYA');
INSERT INTO depo (code, name) VALUES ('0015','PDU - GARUT');
INSERT INTO depo (code, name) VALUES ('0016','INDRAMAYU');
INSERT INTO depo (code, name) VALUES ('0017','PDU');
INSERT INTO depo (code, name) VALUES ('0018','LEMBANG');
INSERT INTO depo (code, name) VALUES ('0019','PDU - CIMAREME');
INSERT INTO depo (code, name) VALUES ('0020','SUBANG');
INSERT INTO depo (code, name) VALUES ('0021','CIPAYUNG');
INSERT INTO depo (code, name) VALUES ('0022','PDU - SUKABUMI');
INSERT INTO depo (code, name) VALUES ('0023','PDU - CIPAYUNG');
INSERT INTO depo (code, name) VALUES ('0024','CIKAMPEK');
INSERT INTO depo (code, name) VALUES ('0025','PDU - SUBANG');
INSERT INTO depo (code, name) VALUES ('0026','KUNINGAN');
INSERT INTO depo (code, name) VALUES ('0027','BANJAR');
