INSERT INTO user (id ,username, password, name, role, active)VALUES ('3','Arahmat','a','ASEP RAHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('4','Iwati','a','IMAS WATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('5','Mmawardi','a','MARTINUS MAWARDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('6','Ysundoro','a','YUSEP SEPUDIN SUNDORO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('7','Fyusfiniawati','a','FIFI YUSFINIAWATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('8','Gginanjar','a','GIN GIN GINANJAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('9','Nsagala','a','NURAFNI SAGALA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('10','Bsusanto','a','BUDI SUSANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('11','Ddarmadi','a','DYKI DARMADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('12','Hmuljadi','a','HIANNY MULJADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('13','Srisnandar','a','SYAEFUL RISNANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('14','Isundari','a','IKA SUNDARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('15','Wmunawaroh','a','WULAN MUNAWAROH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('16','Hsadeli','a','HARI MOCHAMAD SADELI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('17','Shafsah','a','SETIANI HAFSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('18','Rnurfitriani','a','RICA NURFITRIANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('19','Rsevina','a','RANTI FITRI SEVINA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('20','Esakti','a','ERIK NUR BUDI SAKTI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('21','Fh','a','FARID HUSAINI H','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('22','Anugraha','a','ADITHYA NUGRAHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('23','Frahmawati','a','FEBRINA RAHMAWATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('24','Amaulana','a','ARIF IMAM MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('25','Lhana','a','LYDIA HANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('26','Rkadarisma','a','RIZAL KADARISMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('27','Fsalam','a','FIKRI SAIFUL SALAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('28','Pputri','a','PATRICIA VIONA  PUTRI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('29','Kkusnadi','a','KUSNADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('30','Hhermawan','a','HERRY HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('31','Rrasoelin','a','RIKI RASOELIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('32','Arohim','a','ABDUL ROHIM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('33','Rroni','a','RONI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('34','Nkurniasih','a','NIA KURNIASIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('35','Wsetiawan','a','WAWAN SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('36','Akhartiwa','a','ACENG KHARTIWA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('37','Ssutrisno','a','SUTRISNO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('38','Rpratama','a','RENDY PRATAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('39','Dtriadi','a','DIKI TRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('40','Aiwan','a','ASEP IWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('41','Frosdian','a','FASSA DERY ROSDIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('42','Rratmita','a','RATMITA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('43','Mnurohman','a','MAMAN NUROHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('44','Odamayanti','a','OPIE DAMAYANTI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('45','Amaulida','a','ADI TRIA MAULIDA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('46','Ypandu','a','YUDI ARYA PANDU','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('47','Kvalova','a','KIKI DENIS VALOVA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('48','Mdanil','a','M KOMARUDIN DANIL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('49','Nnurdin','a','NURDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('50','Ddaslia','a','DADI DASLIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('51','Erupendi','a','EDI RUPENDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('52','Rramdani','a','RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('53','Iimaduddin','a','ICHSAN IMADUDDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('54','Rsetiawati','a','RISKA SETIAWATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('55','Yrosadi','a','YOEGI PRATAMA ROSADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('56','Dsaputra','a','DEDE MULYANA SAPUTRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('57','Iyudistira','a','INDRA YUDISTIRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('58','Skamaludin','a','SANDI KAMALUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('59','Rsani','a','ROY SANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('60','Rsetiawan','a','RIDWAN SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('61','Mi','a','MOHAMMAD PANJI I','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('62','Inovadiansyah','a','INDRA NOVADIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('63','Ataopik','a','ADE TAOPIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('64','Ufirman','a','UMAR FIRMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('65','Arahayu','a','ADAM RIZKY RAHAYU','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('66','Aridwan','a','AGUS RIDWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('67','Fnugraha','a','FAJAR NUGRAHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('68','Lapriyandi','a','LUKI RESA APRIYANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('69','Iiwan','a','IWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('70','Mwahyudin','a','M IHSAN WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('71','Iisnanial','a','ILHAM PUTRA ISNANIAL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('72','Ssopandi','a','SOPANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('73','Eedih','a','EDIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('74','Dsuryadi','a','DEDI SURYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('75','Ssuparman','a','SUPARMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('76','Ysuwarni','a','YENI SUWARNI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('77','Akurnia','a','ACENG KURNIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('78','Arosikin','a','ASEP ROSIKIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('79','Rsupriatna','a','RAHMAT SUPRIATNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('80','Nsutarna','a','NANANG SUTARNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('81','Asetiawan','a','AGUS SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('82','Dhakim','a','DADAN LUKMANUL HAKIM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('83','Jjumena','a','JAJANG JUMENA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('84','Kkomar','a','KOMAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('85','Nkomara','a','NUNUNG SUTISNA KOMARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('86','Rhermawan','a','RUDI HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('87','Ydarsono','a','YONO DARSONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('88','Dsamud','a','DANI SAMUD','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('89','Csetiawan','a','CUCU SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('90','Ssani','a','SANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('91','Dsuherman','a','DENNY SUWANDY SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('92','Arohmat','a','AYI ROHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('93','Jnurdiansyah','a','JAJANG NURDIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('94','Dsetiawan','a','DEDI SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('95','Ihardiansyah','a','IRVAN HARDIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('96','Dkustana','a','DEDE KUSTANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('97','Daviantara','a','DENI AVIANTARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('98','Itohaerudin','a','ISHAK TOHAERUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('99','Msuratman','a','MAMAN SURATMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('100','Asaepuloh','a','ANDI SAEPULOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('101','Ekh.','a','ERSADNA UMAR KH.','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('102','Aprayoga','a','ANGGI PRAYOGA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('103','Fnugraha','a','FAJAR NUGRAHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('104','Drosid','a','DENI ROSID','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('105','Ilaelasari','a','IIS PUSPITA LAELASARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('106','Amiftahudin','a','AGUS MIFTAHUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('107','Eprasetya','a','EKO PRASETYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('108','Ymulyana','a','YANA MULYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('109','Srusiana','a','SAEPUL RUSIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('110','Tgustian','a','TIA GUSTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('111','Mr','a','MOHAMMAD ARIF R','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('112','Rfauzi','a','REZI MUHAMMAD FAUZI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('113','Dwahyudin','a','DANI WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('114','Fmulyana','a','FERI MULYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('115','Drustandi','a','DENI RUSTANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('116','Tsuntara','a','TONI SUNTARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('117','Hhermawan','a','HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('118','Rfakhri','a','RIZAL ALIYUDDIN FAKHRI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('119','Mm','a','MOCH. ADNAN IDO M','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('120','Nzulmi','a','NIZAR ZULMI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('121','Akoswara','a','ARI KOSWARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('122','Aajat','a','AJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('123','Stardiyono','a','SEPTIYAN TARDIYONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('124','Rmaulana','a','RIZKY MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('125','Hhendrajat','a','HENDI HENDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('126','Snurhadinata','a','SEPTIAN NURHADINATA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('127','Irosapermana','a','INDRA ROSAPERMANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('128','Iramdhani','a','IBNU RAMDHANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('129','Sirfansyah','a','SANTA IRFANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('130','Ywiandani','a','YADI WIANDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('131','Hhandiyansah','a','HANDIYANSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('132','Obasit','a','OBI ABDUL BASIT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('133','Salfarizi','a','SALMAN ALFARIZI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('134','Cjaya','a','CEPI ARDIYANA JAYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('135','Daripin','a','DEDE JENAL ARIPIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('136','Ssupriyatman','a','SUPRIYATMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('137','Rronayurika','a','RIFKI RONAYURIKA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('138','Smunandar','a','SETIA ARIS MUNANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('139','Ahanapi','a','ANDRI IQBAL HANAPI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('140','Ifauji','a','IWAN RIDWAN FAUJI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('141','Amutaqin','a','ADE RAHMAT MUTAQIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('142','Rrosdiana','a','RIKI ROSDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('143','Afauzan','a','AFIF FADHIL FAUZAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('144','Dmalik','a','DANNY MAULANA MALIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('145','Anugraha','a','ARDIAN AHMAD NUGRAHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('146','Rapriana','a','RIAN APRIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('147','Agustian','a','ARIES MAULANA GUSTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('148','Isahrudin','a','IMAN SAHRUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('149','Swinata','a','SYAEFUL FAJAR WINATA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('150','Arachman','a','ANDRIAN RACHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('151','Yramdani','a','YUSUP RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('152','Ihidayat','a','IMAM HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('153','Bdarmansah','a','BUBUN DARMANSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('154','Ysidiq','a','YUSNIAR NUR SYARIF SIDIQ','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('155','Amaulana','a','AGUNG MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('156','Myusup','a','MUHAMAD YUSUP','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('157','Tp','a','THERESIA DINI P','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('158','Lazis','a','LUTHFI AZIS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('159','Lm','a','LUGIA AUGUST M','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('160','Pdwi','a','PANJI ROMADHON DWI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('161','Daripin','a','DENI ARIPIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('162','Nnofiantara','a','NOFIANTARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('163','Lariswandi','a','LUCKY ARISWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('164','Madam','a','MUHAMMAD RIO ADAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('165','Vmaulana','a','VIRLY MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('166','Ccaryono','a','CARYONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('167','Ssutisna','a','SUTISNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('168','Utardi','a','UJANG TARDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('169','Rkusmajadi','a','RUDY KUSMAJADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('170','Akusumah','a','ASEP ANTA KUSUMAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('171','Atohidin','a','ASEP TOHIDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('172','Irusmana','a','IWAN RUSMANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('173','Ckomarsa','a','CEPY KOMARSA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('174','Esutisna','a','ENTIS SUTISNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('175','Asobandy','a','AYI SOBANDY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('176','Dwilanderia','a','DAINE WILANDERIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('177','Nromansah','a','NANO ROMANSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('178','Msobandi','a','MULYADI SOBANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('179','Rlasmana','a','RIAN LASMANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('180','Ragung','a','RAHMAT AGUNG','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('181','Rsupriatna','a','RAMDAN SUPRIATNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('182','Rsobarkah','a','RIKI SOBARKAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('183','Rratmawati','a','RENI RATMAWATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('184','Awahyudi','a','ADE WAHYUDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('185','Fsuraco','a','FANDU SURACO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('186','Tmaga','a','TIRSHA LUKMAN MAGA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('187','Ccepi','a','CEPI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('188','Aace','a','ACE','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('189','Ams','a','ASEP DODI IRAWAN MS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('190','Amaulana','a','ASEP RIYAN MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('191','Ehermawan','a','EKI HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('192','Rkusnandar','a','RONA KUSNANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('193','Asuherman','a','AGUS SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('194','Rsaputra','a','RIDIANSA SAPUTRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('195','Dnugraha','a','DWIKKY NUGRAHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('196','Sh','a','SIGIT MUHAMMAD H','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('197','Rkurniawan','a','RONI KURNIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('198','Jsulaeman','a','JAJANG SULAEMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('199','Ymardiansyah','a','YAYAN MARDIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('200','Jrosadi','a','JAJANG ROSADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('201','Nm','a','NICKO CATUR DALI M','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('202','Falgifari','a','FATHU DZAR ALGIFARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('203','Mbarokah','a','MOCH GAGAH BAROKAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('204','Tsulaeman','a','TATAN SULAEMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('205','Baldi','a','BIMA MUHAMAD ALDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('206','Rriyati','a','RIA NUR RIYATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('207','Ddendi','a','DENDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('208','Piskandar','a','PERI ISKANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('209','Aprawoto','a','AGUS PRAWOTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('210','Mmaryusup','a','MARYUSUP','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('211','Tsetiawan','a','TETEN SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('212','Bismawan','a','BUDI ISMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('213','Mdani','a','MAHMUD DANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('214','Drahmat','a','DARMAWAN RAHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('215','Asahidi','a','AGUS SAHIDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('216','Drahmat','a','DUDI RAHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('217','Esuryadi','a','EDI SURYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('218','Aichsani','a','AAN  ICHSANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('219','Ysupriyadi','a','YUDHI SUPRIYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('220','Nramdani','a','NIKI RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('221','Ssolihin','a','SOLIHIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('222','Therdianto','a','TOTO HERDIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('223','Thermansyah','a','TATA HERMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('224','Afriyadi','a','ADI FRIYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('225','Cmulyana','a','CICI MULYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('226','Jsudrajat','a','JAJAT SUDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('227','Srosa','a','SUNTARA ROSA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('228','Wruswandi','a','WANDI RUSWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('229','Isukmawan','a','ICU SUKMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('230','Ajulianto','a','ANTON JULIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('231','Dsamsudin','a','DEDE SAMSUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('232','Tkustiadi','a','TEDI KUSTIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('233','Tansori','a','TONI ANSORI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('234','Ybahtiar','a','YUSUF BAHTIAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('235','Dramdani','a','DANI GAHA RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('236','Dherdiana','a','DEVI HERDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('237','As','a','ASEP RULLY CAHYA S','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('238','Rkusumah','a','RENDY WIJAYA KUSUMAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('239','Akristian','a','ARGIL KRISTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('240','Dpratama','a','DERIL RENGGA PRATAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('241','Ataopik','a','AGUS TAOPIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('242','Wpratama','a','WANDI ARI PRATAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('243','Mresmana','a','MUHAMMAD ZHANNA RESMANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('244','Awibowo','a','ADAM GALIH WIBOWO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('245','Iruswandi','a','IYUS RUSWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('246','Bnoviansyah','a','BAYU NOVIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('247','Ss','a','SATRIA PERMANA S','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('248','Dkasno','a','DEDE KASNO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('249','Agunawan','a','ASEP ALDI GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('250','Ysuhaya','a','YAYA SUHAYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('251','Eedi','a','EDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('252','Fhamjah','a','FAISAL HAMJAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('253','Bfebrianto','a','BILLY FEBRIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('254','Pramdhani','a','PERDHAN HARI RAMDHANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('255','Ohermawan','a','OPIN HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('256','Aradiansyah','a','ADE RADIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('257','Gn','a','GILANG YOGA N','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('258','Mmulyadi','a','MULYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('259','Eence','a','ENCE','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('260','Bkuswanto','a','BAMBANG KUSWANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('261','Dhabudin','a','DIDIN HABUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('262','Srohman','a','SAEFUL ROHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('263','Ahidayat','a','ASEP AJAT HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('264','Dfirmansyah','a','DENI FIRMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('265','Ssunendi','a','SUNENDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('266','Ataryana','a','AGUS ENDANG TARYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('267','Kkiswanto','a','KISWANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('268','Uruhiyat','a','UYAT RUHIYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('269','Gforestiani','a','GINI FORESTIANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('270','Afebrian','a','ANGGA FEBRIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('271','Smilah','a','SAEPUL MILAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('272','Fi','a','FEBY NURHASANAH I','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('273','Ftaufik','a','FIRMAN TAUFIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('274','Ccahya','a','CAHYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('275','Iridwanudin','a','IWAN RIDWANUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('276','Ymaulana','a','YUSRIZAL MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('277','Ahardiono','a','AGUS HARDIONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('278','Hgunawan','a','HARRY GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('279','Dtriadi','a','DENIH TRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('280','Whendriawan','a','WAWAN HENDRIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('281','Ekamaludin','a','ENANG KAMALUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('282','Rsetiawan','a','RAHMAT SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('283','Dsupriadi','a','DANIEL SUPRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('284','Ihidayat','a','INDRA AHMAD HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('285','Wsopyan','a','WAWAN SOPYAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('286','Dhermawan','a','DADANG HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('287','Asudrajat','a','AJAT SUDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('288','Hsutisna','a','HARRY SUTISNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('289','Hprasetyo','a','HERRY PRASETYO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('290','Nsuryani','a','NANI SURYANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('291','Mridwan','a','MOH. RIDWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('292','Airhamda','a','AUGUSTAN IRHAMDA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('293','Msodik','a','MOCHAMAD SODIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('294','Isiswanto','a','INDRA SISWANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('295','Isopian','a','IPAN SOPIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('296','Alawan','a','ADIL LAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('297','Amursiddiansyah','a','AGUNG MURSIDDIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('298','Dsaepudin','a','DEDI SAEPUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('299','Mramdan','a','MUHAMAD RAMDAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('300','Ngunawan','a','NIDA HANIFA GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('301','Ifirmansyah','a','IRFAN FIRMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('302','Haziz','a','HANISBA AL AZIZ','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('303','Lhermawan','a','LILI  HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('304','Tsuherman','a','TETEN SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('305','Uwasid','a','UJANG WASID','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('306','Usutardi','a','USEP SUTARDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('307','Dzuchrifiandy','a','DEILY ZUCHRIFIANDY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('308','Eenco','a','ENCO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('309','Ooman','a','OMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('310','Ukusnadi','a','UJANG KUSNADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('311','Sgozali','a','SYIRAJUDIN GOZALI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('312','Lkusmara','a','LADI KUSMARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('313','Ahendra','a','ASEP HENDRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('314','Asaripudin','a','AEP SARIPUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('315','Dsetiabudi','a','DEDI SETIABUDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('316','Asarifuloh','a','ADE SARIFULOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('317','Jjuhendri','a','JUHENDRI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('318','Utaryana','a','UJANG TARYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('319','Wsetyawan','a','WAWAN SETYAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('320','Ihidayat','a','IRPAN HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('321','Rrukmana','a','RONI RUKMANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('322','Aperwira','a','ALIP SORGA PERWIRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('323','Rjanuary','a','RIZKY JANUARY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('324','Aaksoni','a','AKSONI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('325','Emariana','a','ENNY MARIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('326','Rseptiana','a','RIZKI SEPTIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('327','Ahidayat','a','ANDI HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('328','Asetiawan','a','ARI SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('329','Dsuryadi','a','DENI SURYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('330','Cmulyana','a','CAHYA MULYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('331','Esuhendar','a','EDEN SUHENDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('332','Jwahyudin','a','JAJANG WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('333','Ysujana','a','YANG YANG SUJANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('334','Grasilandy','a','GIAR RASILANDY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('335','Yagustia','a','YOGA AGUSTIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('336','Dsunandar','a','DANI SUNANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('337','Ahadian','a','ACHMAD HADIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('338','Rchristian','a','RICKY CHRISTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('339','Gnurrahman','a','GUMILAR NURRAHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('340','Aristiadi','a','ANDRES RISTIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('341','Ajuhari','a','ARI JUHARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('342','Igunawan','a','IWAN GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('343','Hhermansah','a','HERMANSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('344','Fferiyanto','a','FERIYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('345','Orimawan','a','OKKY RIMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('346','Gzatnika','a','GALUR ZATNIKA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('347','Esutian','a','ELAN TIAN SUTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('348','Apitriadi','a','ARI PITRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('349','Mpauzi','a','M. IQBAL NURUL PAUZI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('350','Yyanto','a','YANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('351','Idaryana','a','IYAN DARYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('352','Ywahyudi','a','YUDI WAHYUDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('353','Fm','a','FITRI RAHMATIA M','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('354','Cinfantri','a','CEFI INFANTRI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('355','Ffauzi','a','FAJAR PRADANA FAUZI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('356','Ykomaruloh','a','YUNUS KOMARULOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('357','Ddarusalam','a','DADAN DARUSALAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('358','Dputra','a','DENIS ANDRIA EL PUTRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('359','Nkarmila','a','NITA KARMILA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('360','Obagja','a','OKA KHAERUL BAGJA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('361','Dm','a','DINDIN SYAMSUDIN M','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('362','Nnurhamzah','a','NURHAMZAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('363','Dadya','a','DERY ADYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('364','Syulianto','a','SANDI YULIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('365','Dharyadi','a','DIKI HARYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('366','Ssulaeman','a','SULAEMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('367','Mramdan','a','MUHAMAD RAMDAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('368','Amuharam','a','AHMAD NUGRAHA MUHARAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('369','Wwardani','a','WIWIN HIKMAH WARDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('370','Rsusanti','a','ROSA MANGGARANI SARI SUSANTI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('371','Adwiguna','a','AGUNG DWIGUNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('372','Ma','a','MUHAMMAD RIYANDHI A','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('373','Dwahidin','a','DINDIN WAHIDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('374','Ddadan','a','DADAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('375','Hs','a','HILMAN SAEPUDIN IKIN S','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('376','Ragustian','a','ROY SANDI AGUSTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('377','Kpahlevi','a','KAUTSAR SYAH PAHLEVI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('378','Wwiratmana','a','WAWAN WIRATMANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('379','Mfauzan','a','MOCH. RYANDA FAUZAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('380','Sseptian','a','SEPTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('381','Llasemo','a','LASEMO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('382','Ssudisman','a','SUDISMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('383','Ssuherman','a','SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('384','Ikurniatiningsih','a','IMAS KURNIATININGSIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('385','Ttaryana','a','TATA TARYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('386','Rrahmat','a','RAHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('387','Ssuryadi','a','SURYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('388','Usuryana','a','UUN SURYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('389','Ds.','a','DIYAH MUKTI S.','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('390','Iiyan','a','IYAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('391','Asuherman','a','AYI SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('392','Jsianturi','a','JULI SIANTURI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('393','Rritaningsih','a','RITANINGSIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('394','Rajiani','a','RIYAN AJIANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('395','Ssukamto','a','SUKAMTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('396','Mmisar','a','MISAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('397','Jjanudin','a','JANUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('398','Ssuryana','a','SURYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('399','Rhidayat','a','ROMI HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('400','Uermawan','a','UCU ERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('401','Hpurwantoro','a','HADI PURWANTORO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('402','Rbhaehaky','a','RONI BHAEHAKY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('403','Ataufik','a','AGUS TAUFIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('404','Hcipta','a','HENDRA CIPTA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('405','Ysuhana','a','YANA SUHANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('406','Aayep','a','AYEP','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('407','Unurdin','a','USEP NURDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('408','Asuheri','a','ADE SUHERI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('409','Aruhiyat','a','ASEP RUHIYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('410','Hhardiyanto','a','HARDIYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('411','Rpurnama','a','RONI YAHYA PURNAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('412','Dsaepudin','a','DEDIN SAEPUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('413','Cferipuandi','a','CARLY FERIPUANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('414','Rpurnama','a','RIDWAN PURNAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('415','Amulyadi','a','ASEP MULYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('416','Rpratama','a','RIZAL ADITYA PRATAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('417','Dagung','a','DICKY SOFYAN AGUNG','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('418','Sqohhar','a','SAEPUL QOHHAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('419','Dtriwardani','a','DINAR TRIWARDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('420','Ggunawan','a','GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('421','Ddarmawan','a','DANY DARMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('422','Rhidayat','a','RAHMAT HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('423','Rrismawan','a','RISMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('424','Cpirmansyah','a','CHEPY PIRMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('425','Osopandi','a','OPAN SOPANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('426','Rtaufik','a','RISWAN TAUFIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('427','Inuryansah','a','IRHAM NURYANSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('428','Dhermawan','a','DADANG HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('429','Osetiadi','a','OGI SETIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('430','Esupardi','a','ERIK SUPARDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('431','Striyana','a','SEPTI TRIYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('432','Ckuswara','a','CECEP KUSWARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('433','Dtaufik','a','DEDEN TAUFIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('434','Asupriyadi','a','ANDRIANA SUPRIYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('435','Nnurdiana','a','NURDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('436','Arohman','a','ABDUL ROHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('437','AsaIddin','a','AYI SAIDDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('438','Sandriansah','a','SAEFUL ANDRIANSAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('439','Mnainggolan','a','MARUDUT NAINGGOLAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('440','Tardi','a','TEDI ARDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('441','Sf','a','SANDY MOCHAMAD F','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('442','Aasiruddin','a','AAS ASIRUDDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('443','Dnuralamsyah','a','DIKI NURALAMSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('444','Abudiman','a','ARIEF JOHAN BUDIMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('445','Asudrajat','a','AHMAD SUDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('446','Hsantosa','a','HARI SANTOSA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('447','Pfj','a','PRISCILLA NATALIA FJ','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('448','Rhartaman','a','RUDI RICKY HARTAMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('449','Imaulana','a','IPAR FITRA MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('450','Jwahyudin','a','JENI WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('451','Eh','a','ENCEP TAUFIK H','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('452','Dramdani','a','DENDI RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('453','Rsantoso','a','RIKCY HADI SANTOSO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('454','Shidayatulloh','a','SYARIF HIDAYATULLOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('455','Omuhtiar','a','OLIH MUHTIAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('456','Aramdhani','a','ANDHIKA RAMDHANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('457','Isetiaji','a','INDRA SETIAJI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('458','Ksolihin','a','KURNIAWAN SOLIHIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('459','Mghyfari','a','MUHAMAD GHYFARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('460','Dsetiawan','a','DEO AMI SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('461','Jirwanda','a','JAKA IRWANDA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('462','Dkusdinar','a','DEDEN KUSDINAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('463','Srustam','a','SANDI RUSTAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('464','Psopandi','a','PAISAL SOPANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('465','Akoswara','a','AYI KOSWARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('466','Rsepriadi','a','RICKY SEPRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('467','Ihendryana','a','INDRA ADITYA HENDRYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('468','Sp','a','SURYA MEGARIAWAN P','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('469','Amargiana','a','ARIEF MARGIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('470','Anuryana','a','AGUNG NURYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('471','Mfauzi','a','MUHAMAD SAHRUL FAUZI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('472','Nsumpena','a','NANDI SUMPENA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('473','Asugilar','a','ASEP RACHMAT SUGILAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('474','Fh','a','FIQRI RAMADHAN H','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('475','Dandiana','a','DANDI ANDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('476','Rs','a','RAIHAN AZIZ EKA S','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('477','Ma','a','MUHAMAD LUTHFI A','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('478','Afirmansyah','a','ASEP FIRMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('479','Yrahmat','a','YONI RAHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('480','Ksubagja','a','KIKI SUBAGJA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('481','Asuherman','a','ANWAR SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('482','Ihamdani','a','ILHAM HAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('483','Aassadanah','a','ALGI GIFARI ASSADANAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('484','Ssupriatna','a','SUPRIATNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('485','Dsetiawan','a','DADAN SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('486','Yhidayat','a','YAYAT HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('487','Agumilar','a','ANGGA GUMILAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('488','Hwahyudin','a','HENDRA DARMA WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('489','Hapriatna','a','HENDRA APRIATNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('490','Hprajani','a','HARLIAWAN PRAJANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('491','Ggunaedi','a','GUNAEDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('492','Mmaman','a','MAMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('493','Hheni','a','HENI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('494','Usupriadi','a','USE SUPRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('495','Dkurniawan','a','DIDING KURNIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('496','Mmuslih','a','MUSLIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('497','Oriyanto','a','OMAR RIYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('498','Landriana','a','LUSY ANDRIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('499','Nsupriadi','a','NANDI SUPRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('500','Yikhsan','a','YOGA DANIAL IKHSAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('501','Dsudrajat','a','DEDE SUDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('502','Rhidayat','a','RAKHMAT HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('503','Jhermawan','a','JAJANG HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('504','Esuherlan','a','ERLAN SUHERLAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('505','Arohmat','a','ASEP SAEPUL ROHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('506','Eerwin','a','ERWIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('507','Asudrajat','a','ACHMAD AGUNG SUDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('508','Usupiyandi','a','UJANG SUPIYANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('509','Daldevicha','a','DENA ALDEVICHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('510','Mmuslihin','a','MUSLIHIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('511','Fsopian','a','FIAN SOPIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('512','Dfirmansyah','a','DEDEN FIRMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('513','Wkusmawan','a','WAWAN KUSMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('514','Asetyaman','a','ANDY SETYAMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('515','Aanwari','a','ANDRI ANWARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('516','Dhamdani','a','DANI HAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('517','Ifirmansyah','a','IMAN FIRMANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('518','Barwansyah','a','BUDI ARWANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('519','Iramdani','a','IRFAN RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('520','Iikmal','a','IKMAL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('521','Eagustian','a','EGI AGUSTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('522','Eedi','a','EDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('523','Tteguh','a','TEGUH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('524','Asugianto','a','ARIS SUGIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('525','Tsetiadi','a','TEDI SETIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('526','Thandoyo','a','TRI HANDOYO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('527','Mgunawan','a','MUHAMMAD GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('528','Am','a','ADI MUHAMMAD M','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('529','Mgunawan','a','M. SOPIAN GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('530','Sadiyana','a','SYAHRUL ADIYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('531','Mrezaldi','a','MUHAMAD REZALDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('532','Jjakaria','a','JAKARIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('533','Cjulvian','a','CANDRA JULVIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('534','Jdeirawadi','a','JAUHARI DEIRAWADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('535','Asugihyanto','a','ASEP SUGIHYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('536','Amunandar','a','ARIS MUNANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('537','Asukiman','a','ANFAL SUKIMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('538','Apangestu','a','ANDIKA PANGESTU','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('539','Anurulloh','a','ASEP NURULLOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('540','Asuherman','a','ADE SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('541','Ppurnama','a','PURNAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('542','Hbudianto','a','HENKY BUDIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('543','Asyarip','a','ASEP ROHMAN SYARIP','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('544','Wwawan','a','WAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('545','Amulyani','a','AHMAD MULYANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('546','Framdhani','a','FAJAR RAMDHANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('547','Hharispah','a','HARISPAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('548','Mh','a','MOHAMAD TAUFIK H','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('549','Rrizkiansyah','a','RIZKIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('550','Wutari','a','WIDI UTARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('551','Fwarga','a','FERI ALI WARGA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('552','Sulubis','a','SARIP ULUBIS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('553','Vsulistianawaty','a','VINA SULISTIANAWATY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('554','AsaAtullael','a','ALFAN SAATULLAEL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('555','Mhalim','a','MUHAMMAD AINUL HALIM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('556','Nsunandar','a','NANDAR SUNANDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('557','Mfadillah','a','M. IDHAM FADILLAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('558','Mhidayat','a','MUHAMMAD WAHYUDIN HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('559','Btriharyanto','a','BAMBANG TRIHARYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('560','Afaturrohman','a','ANGGI FATURROHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('561','Rsutriyadi','a','ROBBY SUTRIYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('562','Iaji','a','IBRAHIM AJI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('563','Shartadi','a','SUSILO HARTADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('564','Ihermawan','a','IWAN HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('565','Ftaufik','a','FIKI TAUFIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('566','Asaepudin','a','AEP SAEPUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('567','Irosini','a','IDA ROSINI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('568','Ddadan','a','DADAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('569','Isuhendar','a','IRVAN SUHENDAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('570','Ysupiandi','a','YUSUF SUPIANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('571','Ywijaya','a','YUSUP SULTA WIJAYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('572','Ssahrudin','a','SAHRUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('573','Ajaelani','a','ALAN JAELANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('574','Bbeni','a','BENI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('575','Pyuliana','a','PUTRI GINA YULIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('576','Wawaludin','a','WILDAN AWALUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('577','Hhasanudin','a','HASANUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('578','Mhoeruddin','a','MAHMUD HOERUDDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('579','Uwahyudin','a','UJANG WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('580','Lsaepi','a','LAJI AJIZI SAEPI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('581','My','a','M ANDI KSATRIYA K Y','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('582','Aramdani','a','ANDI RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('583','Aandrei','a','ALVIQ RUBELLUS ANDREI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('584','Jwisnu','a','JANUAR WISNU','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('585','Aseftian','a','ANDRI SEFTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('586','Adarmawan','a','ARMAN KIKI DARMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('587','Hsopandi','a','HANDI SOPANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('588','Farkan','a','FAJAR SYAEFUL ARKAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('589','Rsebastian','a','RYAN SEBASTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('590','Asopyan','a','ASEP SOPYAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('591','Ddadang','a','DADANG','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('592','Bsenjoyo','a','BAYU SAPUTRO SENJOYO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('593','Asalam','a','ARDI SALAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('594','Mlomri','a','MUHAMAD LOMRI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('595','Muce','a','MUHAMAD UCE','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('596','Brubianto','a','BEBEN RUBIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('597','Sslamet','a','SLAMET','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('598','Mmustopa','a','MUSTOPA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('599','Aamilin','a','AMILIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('600','Asuryana','a','ACIN SURYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('601','Aafandi','a','ABUNG AFANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('602','Ayusuf','a','ACHMAD YUSUF','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('603','Lsuhardi','a','LILIK SUHARDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('604','Hsoegiharto','a','HERMAN SOEGIHARTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('605','Psaripin','a','PIPIN SARIPIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('606','Otaryono','a','ONO TARYONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('607','Yyusmantoro','a','YUSMANTORO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('608','Ajulian','a','AGUNG DWI RIZKY JULIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('609','Haripin','a','HUSNUL MUHAMAD ARIPIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('610','Shidayat','a','SETIANDI HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('611','Iiryas','a','IRWAN IRYAS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('612','Isuherman','a','IMAN SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('613','Iidayat','a','IDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('614','Nnurhidayatullah','a','NURHIDAYATULLAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('615','Ehermawan','a','ENJANG HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('616','Dirawan','a','DENI IRAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('617','Esobarna','a','ENDANG SOBARNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('618','Aagustina','a','AGUSTINA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('619','Nsuntara','a','NANANG SUNTARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('620','Azaeni','a','ADVAN ZAENI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('621','Dmartono','a','DENI MARTONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('622','Ssuwandi','a','SUWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('623','Agotama','a','ADITIA GOTAMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('624','Tkarya','a','TRISNO KARYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('625','Hseptian','a','HERLI SEPTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('626','Sfaujiah','a','SYFA FAUJIAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('627','Marifin','a','M. ARIFIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('628','Ffauzi','a','FIAN FAUZI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('629','Rhidayat','a','RAHMAT HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('630','Trahmania','a','TRIS RAHMANIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('631','Npebriawan','a','NIKO PEBRIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('632','Wk','a','WAWAN K','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('633','Lkuncoro','a','LINGGAR SARWO KUNCORO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('634','Anugraha','a','ANGGI NUGRAHA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('635','Rfriskiawan','a','RIAN FRISKIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('636','Gprimaryana','a','GESA PRIMARYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('637','Msabqi','a','MOHAMMAD SABQI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('638','Ikustian','a','IYAN KUSTIAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('639','Criyana','a','CANDRA RIYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('640','Rripan','a','RIPAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('641','Wgunawan','a','WAWAN GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('642','Dhermawan','a','DEDEN HERMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('643','Akomarudin','a','ADI KOMARUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('644','Banggara','a','BAYU CHAYA ANGGARA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('645','Nnajamudin','a','NAJAMUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('646','Yyanto','a','YUDI YANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('647','Hsaefulloh','a','HARI SAEFULLOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('648','Kkusdiana','a','KUSDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('649','Ccahyono','a','CAHYONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('650','Ttusmidi','a','TUSMIDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('651','Gnurdin','a','GUMPAY RUDI NURDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('652','Dsutedy','a','DUDI SUTEDY','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('653','Icandraningsih','a','IDA CANDRANINGSIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('654','Dmulyadi','a','DEDI MULYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('655','Agusdiana','a','AGUS GUSDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('656','Asukma','a','AGUNG NUGRAHA SUKMA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('657','Ehaenudin','a','ENUN HAENUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('658','Aridwan','a','AYEP RIDWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('659','Ggustina','a','GUSTINA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('660','Asaepulloh','a','AKBAR SAEPULLOH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('661','Mhartana','a','MULYA HARTANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('662','Ymulyana','a','YUSEP MULYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('663','Hfirdaus','a','HILMAN FIRDAUS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('664','Mmuchtar','a','MUHAMMAD GINANJAR MUCHTAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('665','Madlan','a','MUHAMMAD NUR ADLAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('666','Amalik','a','ABDUL MALIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('667','Bhartanto','a','BERTA WAHYU HARTANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('668','Mn','a','MOCHAMAD RIZKI N','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('669','Ahimawan','a','ALDY PUJI HIMAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('670','Ajuhartono','a','ARIS JUHARTONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('671','Djuwandi','a','DIDI JUWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('672','Airawan','a','AGUS SETIANA IRAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('673','Thidayat','a','TAHYA HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('674','Asukirman','a','AGUS SUKIRMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('675','Kkarsono','a','KARSONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('676','Ssatno','a','SATNO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('677','Ssuharjono','a','SUHARJONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('678','Aabdullah','a','ABDULLAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('679','Wwastiman','a','WASTIMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('680','Lfebriningsih','a','LIESCA NUR FEBRININGSIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('681','Ssobari','a','SOBARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('682','Kkaryono','a','KARYONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('683','Ynitasari','a','YUYUN NITASARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('684','Asanjaya','a','ADI SANJAYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('685','Ikorih','a','IKWAN KORIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('686','Madiya','a','MOHAMMAD ADIYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('687','Mmustofa','a','MUSTOFA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('688','Jsudrajat','a','JAJAT SUDRAJAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('689','Moctaviani','a','MONICA OCTAVIANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('690','Asalim','a','AGUS SALIM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('691','Spetrus','a','SUGIARTO / PETRUS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('692','Ssubagio','a','SUBAGIO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('693','Ssuhadi','a','SUHADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('694','Smulyani','a','SRI MULYANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('695','Smulyadi','a','SADI MULYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('696','Eemon','a','EMON','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('697','Rrianasari','a','RIA APHRODETTY RIANASARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('698','Wwisena','a','WENDY SRI ASTUTI WISENA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('699','Mmeme','a','MEME','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('700','Ssupriadi','a','SUPRIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('701','Aridwan','a','AWAN RIDWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('702','Jjuhani','a','JUHANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('703','Mmardiyana','a','MARDIYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('704','Yarvianto','a','YANTO ARVIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('705','Lliyenti','a','LIYENTI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('706','Hprasetio','a','HENDRO PRASETIO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('707','Dyuniarsih','a','DIAHRATRI YUNIARSIH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('708','Hsahrudin','a','HENDI SAHRUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('709','Mmujayin','a','MUJAYIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('710','Mmustari','a','MUSTARI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('711','Qjaelani','a','QODIR JAELANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('712','Ssadi','a','SADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('713','Ssunaryo','a','SUNARYO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('714','Aadiyana','a','ADIYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('715','Rpratiwi','a','RATNA PRATIWI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('716','Akeswaryanto','a','ADE KESWARYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('717','Hsusanto','a','HENDRA SUSANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('718','Ssarifudin','a','SARIFUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('719','Thermanto','a','TASIDAH HERMANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('720','Ariyadi','a','ADI SLAMET RIYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('721','Apurwanto','a','AKHMAD PURWANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('722','Thidayat','a','TAUFIK HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('723','Hr','a','HILAL MIQDAR R','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('724','Amaya','a','ARIEF MAYA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('725','Dinfantris','a','DIKDIK INFANTRIS','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('726','Ppriyanto','a','PRIYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('727','Phardianto','a','PERI HARDIANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('728','Aandri','a','ANDRI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('729','Skamal','a','SUKRON KAMAL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('730','Malan','a','MUHAMAD ALAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('731','Asugiarto','a','ANTO SUGIARTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('732','Ahidayat','a','AYI HIDAYAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('733','Ccasmita','a','CASMITA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('734','Dramlan','a','DEDE RAMLAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('735','Ssuryana','a','SURYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('736','Mruhimat','a','MAMAT  RUHIMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('737','Dgunawan','a','DEDI GUNAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('738','Llani','a','LANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('739','Ndarsono','a','NONO DARSONO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('740','Isetiawan','a','IWAN SETIAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('741','Bdarusalam','a','BUDI DARUSALAM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('742','Udedi','a','UJANG DEDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('743','Rrahmadi','a','RAHMADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('744','Dsujana','a','DEDE SUJANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('745','Ysuryadi','a','YADI SURYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('746','Ybudiman','a','YUDI BUDIMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('747','Hnurhilman','a','HERNO NURHILMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('748','Bbunyamin','a','BUNYAMIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('749','Amakmur','a','AJANG MAKMUR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('750','Lyuliawati','a','LIA YULIAWATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('751','Ssuherli','a','SONI SUHERLI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('752','Dchandra','a','DICKY CHANDRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('753','Adahlan','a','ALAN DAHLAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('754','Rruswandi','a','RUSWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('755','Asugiarto','a','ARIS SUGIARTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('756','Esetiadi','a','ERIS SETIADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('757','Asaepudin','a','AEP SAEPUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('758','Msuryawan','a','MOHAMMAD SURYAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('759','Ysuryanto','a','YANTO SURYANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('760','Msobar','a','MUHAMAD SOBAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('761','Bnurdiansyah','a','BABANG AKBAR NURDIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('762','Carditia','a','CEPI ARDITIA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('763','Dramdani','a','DANI RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('764','Aramadan','a','ANGGI MALIK RAMADAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('765','Arahman','a','ABDILAH RAHMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('766','Eeswin','a','ESWIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('767','Fwira','a','FERNANDO AHMAD WIRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('768','Triswandi','a','TONI RISWANDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('769','Rmaulana','a','RAMDAN MAULANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('770','Jnurjamil','a','JAMIL NURJAMIL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('771','Iginanjar','a','ILFAN MUHAMAD GINANJAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('772','Rfarid','a','REVLY MIFTAH FARID','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('773','Wwahyudin','a','WAHYUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('774','Sperdana','a','SANDI PERDANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('775','Lramlan','a','LALAN RAMLAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('776','Aputra','a','ANGGA DWI PUTRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('777','Rwardiman','a','RIAN WARDIMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('778','Aruhendi','a','ACEP HENDI RUHENDI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('779','Asumarna','a','ATEP SUMARNA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('780','Aaz','a','ALI PERMANA AZ','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('781','Mfarid','a','MIFTAH FARID','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('782','Vnajila','a','VUJI NAJILA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('783','Agumelar','a','AGUNG GUMELAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('784','Sgemilang','a','SANDI SURYA GEMILANG','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('785','Dshandra','a','DEN GILANG TAOFIK SHANDRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('786','Ajaelani','a','ANWAR JAELANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('787','Atarliana','a','ANDI TARLIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('788','Ssuherman','a','SUHERMAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('789','Umuhtarom','a','USEP TAUFIK MUHTAROM','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('790','Ssaripudin','a','SARIPUDIN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('791','Myendie','a','MUHAMMAD IRFAN YENDIE','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('792','Asudiani','a','ANWAR SUDIANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('793','Ckamil','a','CUCU ANTON KAMIL','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('794','Dsopiyana','a','DANI RIZWAN SOPIYANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('795','Iirbab','a','IRBAB','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('796','Aindrawan','a','ADE INDRAWAN','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('797','Rrahmat','a','RAHMAT','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('798','Sherawati','a','SANTI HERAWATI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('799','Tharyadi','a','TONI HARYADI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('800','Oherdiana','a','OKI HERDIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('801','Dgumelar','a','DEA GUMELAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('802','Rranto','a','RANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('803','Dpertiwi','a','DELLA PERTIWI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('804','Amahardika','a','AGUS MAHARDIKA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('805','Rakbar','a','RAMDANI AKBAR','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('806','Rruswanto','a','RUSWANTO','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('807','Vandriansyah','a','VICKY RIZKY ANDRIANSYAH','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('808','Rmalik','a','RYAN FAUZI MALIK','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('809','Gramdani','a','GILANG RAMDANI','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('810','Grahayu','a','GIN GIN RAHAYU','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('811','Dalpiana','a','DIKA ALPIANA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('812','Rchandra','a','RAFFI CHANDRA','2','1') ;
INSERT INTO user (id ,username, password, name, role, active)VALUES ('813','Lfauzi','a','LUKMAN FAUZI','2','1') ;
